[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; in this version of eesp32 we have to Enable PSRAM

build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cachee-issue


; configuration for 16MB Flash

board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

;--- Additional libraries ---

lib_deps = 
    mathertel/OneButton @ ^2.5.0